### ISSUE TITLE
Invalid SQL for filtering when there are two fields with the same name

### ISSUE THREAD

**Issue by rpiotrow** [gemini-hlsw/gsp-graphql#221]
I prepared a test case which shows the problem: https://github.com/gemini-hlsw/gsp-graphql/compare/main...rpiotrow:filtering-alias-problem

Result of the test is:
```
sbt:gsp-graphql> doobie/testOnly filterjoinalias.FilterJoinAliasSpec
[info] FilterJoinAliasSpec:
[info] - validate
[info] - base query *** FAILED ***
[info]   org.postgresql.util.PSQLException: ERROR: column images3.name_alias_1 does not exist
[info]   Position: 314
[info]   at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2674)
[info]   at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2364)
[info]   at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:354)
[info]   at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:484)
[info]   at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:404)
[info]   at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:162)
[info]   at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
[info]   at doobie.free.KleisliInterpreter$PreparedStatementInterpreter.$anonfun$executeQuery$2(kleisliinterpreter.scala:874)
[info]   at doobie.free.KleisliInterpreter.$anonfun$primitive$2(kleisliinterpreter.scala:113)
[info]   at blocking @ doobie.util.transactor$Transactor$fromDriverManager$.$anonfun$create$1(transactor.scala:355)
[info]   ...
[info] Run completed in 16 seconds, 89 milliseconds.
[info] Total number of tests run: 2
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error] 	filterjoinalias.FilterJoinAliasSpec
[error] (doobie / Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 16 s, completed Jun 24, 2022, 3:13:32 PM
```

The SQL query that is generated is:
```sql
SELECT episodes3.id,
       episodes3.name,
       images3_nested.id_alias_0,
       images3_nested.name_alias_1,
       images3_nested.public_url
FROM episodes3
LEFT JOIN LATERAL
  (SELECT images3.id AS id_alias_0,
          images3.name AS name_alias_1,
          images3.public_url
   FROM images3
   WHERE (episodes3.id = images3.id)
     AND (images3.name_alias_1 = ?) ) AS images3_nested ON (images3_nested.id_alias_0 = episodes3.id)
WHERE (episodes3.id = ?)
```

The name of the query is important, I suspect that this is related to some ordering. When I change the query to `jjj` (needs to be lexicography higher than `images`) test is passing and the resulting query is:
```sql
SELECT images3_nested.id,
       images3_nested.name,
       images3_nested.public_url,
       episodes3.id AS id_alias_0,
       episodes3.name AS name_alias_1
FROM episodes3
LEFT JOIN LATERAL
  (SELECT images3.id,
          images3.name,
          images3.public_url
   FROM images3
   WHERE (episodes3.id = images3.id)
     AND (images3.name = ?) ) AS images3_nested ON (images3_nested.id = episodes3.id)
WHERE (episodes3.id = ?)
```

Changes to pass the test:
```diff
diff --git a/modules/doobie/src/test/scala/filterjoinalias/FilterJoinAliasMapping.scala b/modules/doobie/src/test/scala/filterjoinalias/FilterJoinAliasMapping.scala
index 19f4c94..6780007 100644
--- a/modules/doobie/src/test/scala/filterjoinalias/FilterJoinAliasMapping.scala
+++ b/modules/doobie/src/test/scala/filterjoinalias/FilterJoinAliasMapping.scala
@@ -33,7 +33,7 @@ trait FilterJoinAliasMapping[F[_]] extends DoobieMapping[F] {
   val schema =
     schema"""
       type Query {
-        episode(id: String!): Episode!
+        jjj(id: String!): Episode!
       }
       type Episode {
         id: String!
@@ -64,7 +64,7 @@ trait FilterJoinAliasMapping[F[_]] extends DoobieMapping[F] {
         tpe = QueryType,
         fieldMappings =
           List(
-            SqlRoot("episode")
+            SqlRoot("jjj")
           )
       ),
       ObjectMapping(
@@ -114,9 +114,9 @@ trait FilterJoinAliasMapping[F[_]] extends DoobieMapping[F] {
 
   override val selectElaborator: SelectElaborator = new SelectElaborator(Map(
     QueryType -> {
-      case Select("episode", List(Binding("id", StringValue(id))), child) =>
+      case Select("jjj", List(Binding("id", StringValue(id))), child) =>
         Select(
-          "episode",
+          "jjj",
           Nil,
           Unique(Filter(Eql(UniquePath[String](List("id")), Const(id)), child))
         ).rightIor
diff --git a/modules/sql/src/test/scala/SqlFilterJoinAliasSpec.scala b/modules/sql/src/test/scala/SqlFilterJoinAliasSpec.scala
index ce3f70e..98dd91f 100644
--- a/modules/sql/src/test/scala/SqlFilterJoinAliasSpec.scala
+++ b/modules/sql/src/test/scala/SqlFilterJoinAliasSpec.scala
@@ -23,7 +23,7 @@ trait SqlFilterJoinAliasSpec extends AnyFunSuite {
   test("base query") {
     val query = """
       query {
-        episode(id: "a") {
+        jjj(id: "a") {
           images(filter: { name: "abc" }) {
             inner { name }
           }
@@ -34,7 +34,7 @@ trait SqlFilterJoinAliasSpec extends AnyFunSuite {
     val expected = json"""
       {
         "data" : {
-          "episode" : {
+          "jjj" : {
             "images" : [
               {
                 "inner" : {
```

**Comment by tpolecat** [comment]
Thanks for the detailed report!

**Comment by milessabin** [comment]
The naming issue was actually a red-herring. The problem turned out to be another "name as seen from the inside" vs "name as seen from the outside" wrt to aliasing. Changing the name had the side effect that the offending column no longer needed to be aliased, so the problem went away.
