### ISSUE TITLE
unresolved dependencies upon building

### ISSUE THREAD

**Issue by philipschwarz** [gemini-hlsw/gsp-graphql#366]
Hello,

my very first attempt at compiling with sbt fails as follows (sigh):

```
~/d/g/gsp-graphql (main|✔) $ sbt compile
[info] welcome to sbt 1.8.2 (Homebrew Java 18.0.2.1)
[info] loading global plugins from /Users/philipschwarz/.sbt/1.0/plugins
[info] loading settings for project gsp-graphql-build-build from plugins.sbt ...
[info] loading project definition from /Users/philipschwarz/dev/git/gsp-graphql/project/project
[info] loading settings for project gsp-graphql-build from plugins.sbt ...
[info] loading project definition from /Users/philipschwarz/dev/git/gsp-graphql/project
[info] Updating 
[info] Resolved  dependencies
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.typesafe.sbt:sbt-ghpages:0.6.3 (sbtVersion=1.0, scalaVersion=2.12)
[warn] 		com.typesafe.sbt:sbt-site:1.4.1 (sbtVersion=1.0, scalaVersion=2.12)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.typesafe.sbt:sbt-ghpages;sbtVersion=1.0;scalaVersion=2.12:0.6.3
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-ghpages_2.12_1.0/0.6.3/sbt-ghpages-0.6.3.pom
[error]   not found: /Users/philipschwarz/.ivy2/local/com.typesafe.sbt/sbt-ghpages/scala_2.12/sbt_1.0/0.6.3/ivys/ivy.xml
[error]   checksum format error: /Users/philipschwarz/Library/Caches/Coursier/v1/https/repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-ghpages/scala_2.12/sbt_1.0/0.6.3/ivys/ivy.xml.sha1
[error]   checksum format error: /Users/philipschwarz/Library/Caches/Coursier/v1/https/repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-ghpages/scala_2.12/sbt_1.0/0.6.3/ivys/ivy.xml.sha1
[error] Error downloading com.typesafe.sbt:sbt-site;sbtVersion=1.0;scalaVersion=2.12:1.4.1
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-site_2.12_1.0/1.4.1/sbt-site-1.4.1.pom
[error]   not found: /Users/philipschwarz/.ivy2/local/com.typesafe.sbt/sbt-site/scala_2.12/sbt_1.0/1.4.1/ivys/ivy.xml
[error]   checksum format error: /Users/philipschwarz/Library/Caches/Coursier/v1/https/repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-site/scala_2.12/sbt_1.0/1.4.1/ivys/ivy.xml.sha1
[error]   checksum format error: /Users/philipschwarz/Library/Caches/Coursier/v1/https/repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-site/scala_2.12/sbt_1.0/1.4.1/ivys/ivy.xml.sha1
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:344)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:313)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:313)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3687)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.typesafe.sbt:sbt-ghpages;sbtVersion=1.0;scalaVersion=2.12:0.6.3
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-ghpages_2.12_1.0/0.6.3/sbt-ghpages-0.6.3.pom
[error]   not found: /Users/philipschwarz/.ivy2/local/com.typesafe.sbt/sbt-ghpages/scala_2.12/sbt_1.0/0.6.3/ivys/ivy.xml
[error]   checksum format error: /Users/philipschwarz/Library/Caches/Coursier/v1/https/repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-ghpages/scala_2.12/sbt_1.0/0.6.3/ivys/ivy.xml.sha1
[error]   checksum format error: /Users/philipschwarz/Library/Caches/Coursier/v1/https/repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-ghpages/scala_2.12/sbt_1.0/0.6.3/ivys/ivy.xml.sha1
[error] Error downloading com.typesafe.sbt:sbt-site;sbtVersion=1.0;scalaVersion=2.12:1.4.1
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-site_2.12_1.0/1.4.1/sbt-site-1.4.1.pom
[error]   not found: /Users/philipschwarz/.ivy2/local/com.typesafe.sbt/sbt-site/scala_2.12/sbt_1.0/1.4.1/ivys/ivy.xml
[error]   checksum format error: /Users/philipschwarz/Library/Caches/Coursier/v1/https/repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-site/scala_2.12/sbt_1.0/1.4.1/ivys/ivy.xml.sha1
[error]   checksum format error: /Users/philipschwarz/Library/Caches/Coursier/v1/https/repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-site/scala_2.12/sbt_1.0/1.4.1/ivys/ivy.xml.sha1
```

Before going into yak shaving mode, I thought I'd ask if you have any suggestions on how to address the problem?

Thank you in advance for your help.

**Comment by tpolecat** [comment]
Hm yeah those plugins don't exist at those coordinates anymore. Maybe check their respective repos to see if they changed? Everyone working on this library may just randomly have them in a local cache.

**Comment by tpolecat** [comment]
Actually can you just try again? It looks like a [repo.scala-sbt.org](https://repo.scala-sbt.org/) was down.

**Comment by philipschwarz** [comment]
Unfortunately I still encounter the same problem.

But thank you for looking into this, I appreciate it.

**Comment by milessabin** [comment]
I think you hit https://github.com/sbt/sbt/issues/7202, which I think is resolved now ... give it another try.

**Comment by philipschwarz** [comment]
Thanks, that looked promising, so I tried again, but unfortunately I get the same result:

```
[info] welcome to sbt 1.8.2 (Homebrew Java 18.0.2.1)
[info] loading settings for project gsp-graphql-build-build from plugins.sbt ...
[info] loading project definition from /Users/philipschwarz/dev/git/gsp-graphql/project/project
[info] loading settings for project gsp-graphql-build from plugins.sbt ...
[info] loading project definition from /Users/philipschwarz/dev/git/gsp-graphql/project
[info] Updating 
https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-ghpages/scala_2.12/sbt_1.0/0.6.3/ivys/ivy.xml
  No modified time in response
https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-site/scala_2.12/sbt_1.0/1.4.1/ivys/ivy.xml
  No modified time in response
[info] Resolved  dependencies
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.typesafe.sbt:sbt-ghpages:0.6.3 (sbtVersion=1.0, scalaVersion=2.12)
[warn] 		com.typesafe.sbt:sbt-site:1.4.1 (sbtVersion=1.0, scalaVersion=2.12)
[warn] 
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.typesafe.sbt:sbt-ghpages;sbtVersion=1.0;scalaVersion=2.12:0.6.3
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-ghpages_2.12_1.0/0.6.3/sbt-ghpages-0.6.3.pom
[error]   not found: /Users/philipschwarz/.ivy2/local/com.typesafe.sbt/sbt-ghpages/scala_2.12/sbt_1.0/0.6.3/ivys/ivy.xml
[error]   checksum format error: /Users/philipschwarz/Library/Caches/Coursier/v1/https/repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-ghpages/scala_2.12/sbt_1.0/0.6.3/ivys/ivy.xml.sha1
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-ghpages/scala_2.12/sbt_1.0/0.6.3/ivys/ivy.xml
[error] Error downloading com.typesafe.sbt:sbt-site;sbtVersion=1.0;scalaVersion=2.12:1.4.1
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-site_2.12_1.0/1.4.1/sbt-site-1.4.1.pom
[error]   not found: /Users/philipschwarz/.ivy2/local/com.typesafe.sbt/sbt-site/scala_2.12/sbt_1.0/1.4.1/ivys/ivy.xml
[error]   checksum format error: /Users/philipschwarz/Library/Caches/Coursier/v1/https/repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-site/scala_2.12/sbt_1.0/1.4.1/ivys/ivy.xml.sha1
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-site/scala_2.12/sbt_1.0/1.4.1/ivys/ivy.xml
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:344)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:313)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:313)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3687)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.typesafe.sbt:sbt-ghpages;sbtVersion=1.0;scalaVersion=2.12:0.6.3
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-ghpages_2.12_1.0/0.6.3/sbt-ghpages-0.6.3.pom
[error]   not found: /Users/philipschwarz/.ivy2/local/com.typesafe.sbt/sbt-ghpages/scala_2.12/sbt_1.0/0.6.3/ivys/ivy.xml
[error]   checksum format error: /Users/philipschwarz/Library/Caches/Coursier/v1/https/repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-ghpages/scala_2.12/sbt_1.0/0.6.3/ivys/ivy.xml.sha1
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-ghpages/scala_2.12/sbt_1.0/0.6.3/ivys/ivy.xml
[error] Error downloading com.typesafe.sbt:sbt-site;sbtVersion=1.0;scalaVersion=2.12:1.4.1
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-site_2.12_1.0/1.4.1/sbt-site-1.4.1.pom
[error]   not found: /Users/philipschwarz/.ivy2/local/com.typesafe.sbt/sbt-site/scala_2.12/sbt_1.0/1.4.1/ivys/ivy.xml
[error]   checksum format error: /Users/philipschwarz/Library/Caches/Coursier/v1/https/repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-site/scala_2.12/sbt_1.0/1.4.1/ivys/ivy.xml.sha1
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-site/scala_2.12/sbt_1.0/1.4.1/ivys/ivy.xml
```

**Comment by armanbilge** [comment]
```
[error]   checksum format error: /Users/philipschwarz/Library/Caches/Coursier/v1/https/repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-site/scala_2.12/sbt_1.0/1.4.1/ivys/ivy.xml.sha1
```

I suspect your cache has become corrupted during the blackout. You might try nuking it and trying again.

**Comment by philipschwarz** [comment]
@armanbilge sweet, that did the job - thank you so much! 

```
~/d/g/gsp-graphql (main|✔) $ rm -rf /Users/philipschwarz/Library/Caches/Coursier/v1/https/

~/d/g/gsp-graphql (main|✔) $ ls /Users/philipschwarz/Library/Caches/Coursier/v1/https/
ls: /Users/philipschwarz/Library/Caches/Coursier/v1/https/: No such file or directory

~/d/g/gsp-graphql (main|✔) [1]$ sbt clean compile
[info] welcome to sbt 1.8.2 (Homebrew Java 18.0.2.1)
...
[success] Total time: 53 s, completed 9 Apr 2023, 10:04:59

~/d/g/gsp-graphql (main|✔) $ 
```
